spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Baby980915
    url: jdbc:mysql://rm-2zeff536j939032fb0o.mysql.rds.aliyuncs.com:3306/user_center?useSSL=false
  session:
    timeout: 86400 # session失效时间
#  sql:
#    init:
#      schema-locations: classpath:db/schema-h2.sql
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

